---
title: "Rapid Assessment and ARU processing ~ Owls"
author: "Jeremiah Kennedy"
date: "11/13/2021"
output: html_document
---


## Purpose of Script

If you are looking to process larger volumes of ARU recording data for acoustically active species, this is the place to be. The point of this protocol and these scripts is to provide an open access and easy to personalize tool for identifying and counting sonic wildlife.This process works best for smaller groups of species or 'acoustic clades' (eg. owls, grouse, high-singing warblers, woodpeckers, nocturnal birds), but can be personalized to just about any time frame and frequency range that a researcher is interested in. 

# Broad Steps

1) Evaluate files
2) Produce acoustic indices
3) Evaluate indices visually
4) Produce recording visualizations and metadata
5) Process recordings visually


# Base Scripts (without associated letters eg. 1 not 1a or 1b, 2 not 2a or 2b)
_These scripts are the backbone of this repository. Hypothetically, you should be able to run these scripts alone to process your data, but since ARU data varies so significantly the modifications available in the 'Additional Scripts' section will likely be of use at some point to anyone using this analysis_



****1_rename_and_copy_recordings.R****
- This is an essential step for the PowerShell script. you need to be able to reference the timezone in your filename for the powershell script to work
- If you are running this on non-continuous recordings, this step can also be used to 'fake' a continuous recording schedule


****2_Acoustic_Indices_By_Station.ps1****
-  

****3_Combine_Index_Visualizations.R****

****4_write_spectrograms.R****

# Additional Scripts

****0_Trim_Swift_Files.ps1****

****1a_rename_SM3_recordings.R****

****1b_rename_SWIFT_recordings.R****

****2a_Combine_Indices_By_Station.ps1****

****3a_Individual_Index_Visualizations.R****

****3b_Delete_Image_LDFCS.R****

# Steps and Scripts in detail


"3_Combine_Index_Visualizations - Copy.R"
""
""
""
"4_write_spectrograms - Copy.R"
""
"4_write_spectrograms_no_grid_or_time_consistancy - Copy.R"
"4a_write_spectrograms_no_grid_or_time_consistancy.R"
"4b_write_spectrograms_single_frame.R"
"4?_write_spectrograms_single_frame_SoX.R"
"5_Make_visualizations.ps1"
"5_manipulate_observation_output.R"
""

""
""
""
""





